project:
  type: website

resources:
  - CNAME

website:
  navbar:
    logo: "assets/logo-large.svg"
    left:
      - href: index.qmd
        text: "#SJHPHL"
      - href: about.qmd
        text: About
      - href: events.qmd
        text: Events
      - posts/index.qmd
    right:
      - icon: github
        href: https://github.com/socialjusticehackathon/
      - icon: twitter
        href: https://twitter.com/ssjhackathon
  page-footer:
    left:
      - href: "https://www.eventbrite.com/e/sjhphl-hack-night-prep-for-philadelphia-social-justice-hackathon-tickets-1983381897647"
        text: "Register for event"
      - href: "#"
        text: "Submit a project (coming soon)"
      - href: "mailto:info@socialjusticehackathon.com"
        text: "Become a sponsor"
    background: "#6D157A"
    foreground: "#FFFFFF"
  open-graph:
    title: "Philadelphia Social Justice Hackathon"
    description: "The Philadelphia Social Justice Hackathon will be held at Penn Carey Law School from March 27-29, 2026, to bring students, programmers, and other 'civic-minded hackers' together â€“ to work in collaboration with justice advocates, public servants, community legal providers, and members of the community."
    image: "/assets/preview.png"
    image-height: 500
    image-width: 1500
    image-alt: "A purple banner with the text: Philadelphia's Social Justice Hackathon; Penn Carey Law School; March 27-29"
    locale: en_US
    site-name: "#SJHPHL"
format:
  html:
    theme: styles.scss
